name: Contract tests
on:
  push:
    branches:
      - main
      - release/*

  pull_request:
    branches:
      - main
      - release/*

jobs:
  setup-and-test:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize
        uses: ./.github/actions/initialization

      - name: Run contract tests
        uses: ./.github/actions/contract_tests
        with:
          api-level: 35
