name: Contract tests
on:
  push:
    branches:
      - main
      - release/*

  pull_request:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-15-large

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize
        uses: ./.github/actions/initialization

      - name: Run contract tests
        uses: ./.github/actions/contract_tests
        with:
          api-level: 18
          destination: ios

  # tvos:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 18
  #         destination: tvos
  
  # watchos:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 11
  #         destination: watchos
  
  # visionos:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 2
  #         destination: visionos
