name: Contract tests
on:
  push:
    branches:
      - main
      - release/*

  pull_request:
    branches:
      - main
      - release/*

jobs:
  ios:
    runs-on: macos-15

    # This job will be cancelled after 60 minutes
    timeout-minutes: 60

    # Automatically cancel a running GitHub Actions workflow when a new commit is pushed to the same branch or pull request
    concurrency: 
          group: ios-concurrency-group
          cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize
        uses: ./.github/actions/initialization

      - name: Run contract tests
        uses: ./.github/actions/contract_tests
        with:
          api-level: 18
          destination: ios

  # tvos:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 18
  #         destination: tvos
  
  # watchos:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 11
  #         destination: watchos
  
  # visionos:
  #   runs-on: macos-15
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 2
  #         destination: visionos
