name: Contract tests
on:
  # push:
  #   branches:
  #     - main
  #     - release/**/*

  # pull_request:
  #   branches:
  #     - main
  #     - release/**/*
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-15-xlarge

    # This job will be cancelled after 30 minutes
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Initialize
        uses: ./.github/actions/initialization

      - name: Run contract tests
        uses: ./.github/actions/contract_tests
        with:
          api-level: 18
          destination: ios

  # tvos:
  #   runs-on: macos-15

  #   # This job will be cancelled after 60 minutes
  #   timeout-minutes: 60

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 18
  #         destination: tvos

  # watchos:
  #   runs-on: macos-15

  #   # This job will be cancelled after 60 minutes
  #   timeout-minutes: 60

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 11
  #         destination: watchos

  # visionos:
  #   runs-on: macos-15

  #   # This job will be cancelled after 60 minutes
  #   timeout-minutes: 60

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v5

  #     - name: Initialize
  #       uses: ./.github/actions/initialization

  #     - name: Run contract tests
  #       uses: ./.github/actions/contract_tests
  #       with:
  #         api-level: 2
  #         destination: visionos
